In [1]:
# setup absolute path to location of package Starts and config-file 
from inspect import getsourcefile
import os.path as path, sys
current_dir = path.dirname(path.abspath(getsourcefile(lambda:0)))
sys.path.insert(0, current_dir[:current_dir.rfind(path.sep)])

# import package Starts
from Starts.startvis import *
from Starts.startmodskl import *
from Starts.startvis import *
from Starts.startmodtf import *
%matplotlib inline


local_kwargs {'data_path_1': './data/italy_earthquakes_from_2016-08-24_to_2016-11-30.csv', 'data_path_2': './data/clustered_italy_earthquakes_from_2016-08-24_to_2016-11-30.csv', 'data_path_3': '', 'drop_obj_col': False, 'nan_drop_col': False, 'nan_drop_row': False, 'nan_zero': False, 'nan_mean': True, 'nan_mean_neighbors': False}


Using TensorFlow backend.


In [2]:
# test_data = StartML.convert_time_series(test_data, 'Time')
data = nonan_data.drop(['Time'], axis=1)
data.head()

Latitude  Longitude  Depth/Km  Magnitude  Clusters
0   42.6983    13.2335       8.1        6.0         3
1   42.7123    13.2533       9.0        4.5         3
2   42.7647    13.1723       9.7        3.8         3
3   42.7803    13.1683       9.7        3.9         3
4   42.7798    13.1575       9.7        3.6         3

In [3]:
# init data with target_label = Clusters
stf = StartModTF(data, label='Clusters')
stf

In [4]:
stf.info_parameters()


Hidden_units: [10, 10] 

Optimizer: Adagrad 

Activation_function: relu 

Learning_Rate: 0.001 

Training_Steps: 1000 

Batch_Size: 10 

Number_of_epochs: relu 

Feature_Scaling: False 



In [5]:
# classify data based on label = 'Clusters' and save the results into y_pred and compute accuracy of model
classifier, y_true, y_pred = stf.classifier_estimator(model_lin=True)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': '/tmp/tmpmd0bdiic', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f766d647be0>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 1 into /tmp/tmpmd0bdiic/model.ckpt.
INFO:tensorflow:loss = 13.86

In [6]:
classifier

In [7]:
# Convert the predicted value y_pred and show the metrics_report
final_pred = [pred['class_ids'][0] for pred in list(y_pred)]
StartMod.metrics_report(y_true, final_pred)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /tmp/tmpmd0bdiic/model.ckpt-647
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
Classification Report: 
              precision    recall  f1-score   support

          0       1.00      1.00      1.00       764
          1       1.00      1.00      1.00       253
          2       0.94      1.00      0.97       518
          3       1.00      0.59      0.74        83

avg / total       0.98      0.98      0.98      1618

Confusion Matrix: 
 [[764   0   0   0]
 [  0 253   0   0]
 [  0   0 518   0]
 [  0   0  34  49]]

Accuracy: 
 0.978986402967

Mean_Squared_Error: 
 0.0210135970334


In [8]:
# Predict on new_data 'new_x_true'
# pred_input_func = StartModTF.pred_input_fn(test_features=new_x_true, batch_size=len(new_x_true))
# y_predict = classifier.predict(input_fn=pred_input_func)

In [9]:
# Update parameters 
new_param={'hidden_units':[10,10,10], 'optimizer':'Adam', 'activation_fn':'sigmoid', 'learning_rate': 0.0001,
           'steps':5000, 'batch_size':10, 'num_epochs':10, 'feature_scl':True}
stf.update_parameters=new_param
stf.info_parameters()


Hidden_units: [10, 10, 10] 

Optimizer: Adam 

Activation_function: sigmoid 

Learning_Rate: 0.0001 

Training_Steps: 5000 

Batch_Size: 10 

Number_of_epochs: sigmoid 

Feature_Scaling: True 



In [10]:
# and train model again
classifier, y_true, y_pred = stf.classifier_estimator(model_lin=True)

/usr/lib64/python3.6/site-packages/pandas/core/frame.py:2450: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self[k1] = value[k2]


INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': '/tmp/tmpkdortwad', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f763b9f1160>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 1 into /tmp/tmpkdortwad/model.ckpt.
INFO:tensorflow:loss = 13.86

### By changing (increasing parameters) the accuracy has been improved from 0.980840543881 to 0.99984539

In [17]:
# TODO: plot y_true and y_pred and comment
# y_true.plot()
type(y_true), type(y_pred)
type(stf.data)
stf.data.columns

Index(['Latitude', 'Longitude', 'Depth/Km', 'Magnitude', 'Clusters'], dtype='object')