In [1]:
from startmodtf import *

Using TensorFlow backend.


In [2]:
# test_data = StartML.convert_time_series(test_data, 'Time')
data = test_data.drop(['Time'], axis=1)
data.head()

Latitude  Longitude  Depth/Km  Magnitude  Clusters
0   42.6983    13.2335       8.1        6.0         3
1   42.7123    13.2533       9.0        4.5         3
2   42.7647    13.1723       9.7        3.8         3
3   42.7803    13.1683       9.7        3.9         3
4   42.7798    13.1575       9.7        3.6         3

In [3]:
stf = StartModTF(data, label='Clusters')
stf

In [4]:
stf.info_parameters()


Hidden_units: [10, 10] 

Optimizer: Adagrad 

Activation_function: relu 

Learning_Rate: 0.001 

Training_Steps: 1000 

Batch_Size: 10 

Number_of_epochs: relu 

Feature_Scaling: False 



In [5]:
classifier, y_true, y_pred = stf.classifier_estimator(model_lin=True)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_log_step_count_steps': 100, '_keep_checkpoint_max': 5, '_save_summary_steps': 100, '_task_type': 'worker', '_session_config': None, '_save_checkpoints_steps': None, '_model_dir': '/tmp/tmpf7567nk8', '_service': None, '_tf_random_seed': None, '_task_id': 0, '_save_checkpoints_secs': 600, '_master': '', '_keep_checkpoint_every_n_hours': 10000, '_is_chief': True, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7fcc2692b2e8>, '_num_ps_replicas': 0, '_num_worker_replicas': 1}
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Saving checkpoints for 1 into /tmp/tmpf7567nk8/model.ckpt.
INFO:tensorflow:loss = 13.862944, step = 1
INFO:tensorflow:global_step/sec: 394.712
INFO:tensorflow:loss = 5.0818753, step = 101 (0.263 sec)
INFO:tensorflow:global_step/sec: 350.053
INFO:tensorflow:loss = 7.1687403, step = 201 (0.276 sec)
INFO:tensorflow:global_step/sec: 387.141
INFO:tensorflow:loss =

In [6]:
classifier

In [7]:
final_pred = [pred['class_ids'][0] for pred in list(y_pred)]
StartMod.metrics_report(y_true, final_pred)

INFO:tensorflow:Restoring parameters from /tmp/tmpf7567nk8/model.ckpt-647
Classification Report: 
              precision    recall  f1-score   support

          0       1.00      1.00      1.00       764
          1       1.00      1.00      1.00       256
          2       0.99      1.00      0.99       515
          3       1.00      0.93      0.96        83

avg / total       1.00      1.00      1.00      1618

Confusion Matrix: 
 [[764   0   0   0]
 [  0 256   0   0]
 [  0   0 515   0]
 [  0   0   6  77]]


In [8]:
# Predict on new_data 'new_x_true'
# pred_input_func = StartModTF.pred_input_fn(test_features=new_x_true, batch_size=len(new_x_true))
# y_predict = classifier.predict(input_fn=pred_input_func)

In [9]:
# Update parameters 
new_param={'hidden_units':[10,10,10], 'optimizer':'Adam', 'activation_fn':'sigmoid', 'learning_rate': 0.0001,
           'steps':5000, 'batch_size':10, 'num_epochs':10, 'feature_scl':True}
stf.update_parameters=new_param
stf.info_parameters()


Hidden_units: [10, 10, 10] 

Optimizer: Adam 

Activation_function: sigmoid 

Learning_Rate: 0.0001 

Training_Steps: 5000 

Batch_Size: 10 

Number_of_epochs: sigmoid 

Feature_Scaling: True 



In [10]:
# and train model again
classifier, y_true, y_pred = stf.classifier_estimator(model_lin=True)

/usr/lib64/python3.5/site-packages/pandas/core/frame.py:2540: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self[k1] = value[k2]


INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_log_step_count_steps': 100, '_keep_checkpoint_max': 5, '_save_summary_steps': 100, '_task_type': 'worker', '_session_config': None, '_save_checkpoints_steps': None, '_model_dir': '/tmp/tmpgys5z1bn', '_service': None, '_tf_random_seed': None, '_task_id': 0, '_save_checkpoints_secs': 600, '_master': '', '_keep_checkpoint_every_n_hours': 10000, '_is_chief': True, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7fcc176b8048>, '_num_ps_replicas': 0, '_num_worker_replicas': 1}
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Saving checkpoints for 1 into /tmp/tmpgys5z1bn/model.ckpt.
INFO:tensorflow:loss = 13.862944, step = 1
INFO:tensorflow:global_step/sec: 257.834
INFO:tensorflow:loss = 8.062078, step = 101 (0.394 sec)
INFO:tensorflow:global_step/sec: 277.019
INFO:tensorflow:loss = 4.288229, step = 201 (0.364 sec)
INFO:tensorflow:global_step/sec: 534.05
INFO:tensorflow:loss = 4.

### By changing (increasing parameters) the accuracy has been improved from 0.99489796 to 0.9998454