### Try Model: Polynomial Linear Regression

In [1]:
from startmodskl import *

In [2]:
nonan_data.head()

Survived  Pclass  Sex   Age     Fare  Title  FamilySize
0         0       3    1  21.0   8.0500      5           0
1         0       1    1  47.0  25.5875      5           0
2         1       2    0   5.0  27.7500      4           3
3         0       3    1  49.0   0.0000      5           0
4         0       3    1  36.0   0.0000      5           0

In [3]:
# Choose method Polynomial Linear Regression to predict the Survivors
regressor_poly, y_true, y_pred = StartModSKL.regression_linear(nonan_data, 'Survived', poly=True)

regressor_poly

PolynomialFeatures(degree=3, include_bias=True, interaction_only=False)

In [4]:
# Convert predicted value by rounding it (>0.5 will be considered as 1 else 0)
y_pred = np.array([1 if item>0.5 else 0 for item in y_pred ])

# Compare the predicted value with true_value
len(y_true), len(y_pred)
y_true, y_pred

(array([0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0,
        0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1,
        1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1,
        1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
        1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
        1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1,
        0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 0, 1]),
 array([0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1,
        0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0,
        0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1,
        1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
        1, 0, 1, 0,

In [5]:
confusion_matrix(y_true, y_pred)

array([[83, 15],
       [31, 50]])

### Result: 
#### the correct predicted result 133, 
#### the wrong predicted result 46