In [1]:
# DEBUG FILE

In [2]:
# Configuration: setup absolute path to location of package Starts and config-file 
from inspect import getsourcefile
import os.path as path, sys
current_dir = path.dirname(path.abspath(getsourcefile(lambda:0)))
sys.path.insert(0, current_dir[:current_dir.rfind(path.sep)])

from Starts.start import *
from Starts.startml import *
from Starts.startvis import *  
%matplotlib inline
rcParams['figure.figsize'] = 20, 6#

# error_day: 286 11-04-2020

Start importing files in folder
['.gitignore', '01-22-2020.csv', '01-23-2020.csv', '01-24-2020.csv', '01-25-2020.csv', '01-26-2020.csv', '01-27-2020.csv', '01-28-2020.csv', '01-29-2020.csv', '01-30-2020.csv', '01-31-2020.csv', '02-01-2020.csv', '02-02-2020.csv', '02-03-2020.csv', '02-04-2020.csv', '02-05-2020.csv', '02-06-2020.csv', '02-07-2020.csv', '02-08-2020.csv', '02-09-2020.csv', '02-10-2020.csv', '02-11-2020.csv', '02-12-2020.csv', '02-13-2020.csv', '02-14-2020.csv', '02-15-2020.csv', '02-16-2020.csv', '02-17-2020.csv', '02-18-2020.csv', '02-19-2020.csv', '02-20-2020.csv', '02-21-2020.csv', '02-22-2020.csv', '02-23-2020.csv', '02-24-2020.csv', '02-25-2020.csv', '02-26-2020.csv', '02-27-2020.csv', '02-28-2020.csv', '02-29-2020.csv', '03-01-2020.csv', '03-02-2020.csv', '03-03-2020.csv', '03-04-2020.csv', '03-05-2020.csv', '03-06-2020.csv', '03-07-2020.csv', '03-08-2020.csv', '03-09-2020.csv', '03-10-2020.csv', '03-11-2020.csv', '03-12-2020.csv', '03-13-2020.csv', '03-14-2020.csv',

In [3]:
today_is=files[-2].split('.')[0]
today_is

'11-13-2020'

In [4]:
# x-axis (days) for plot
x_dat = np.arange(len(data))

# Pre-Processing: fill all NaN with 0
data = [data[day].fillna(0) for day in x_dat]

# collect all data into list all countries of tuple (country, confirmed), (country, fatalities), (country, recovered)
countries = sdata['Country_Region'].unique()

infected_countries_latest = np.unique(data[-1][data[-1]['Confirmed']>0].filter(regex=("Country.*")).values)

num_infected_countries = [len(np.unique(data[day][data[day]['Confirmed']>0].filter(regex=("Country.*")).values)) for day in x_dat]

all_countries = dict()
all_countries_Confirmed = dict()
all_countries_Deaths = dict()
all_countries_Recovered = dict()
all_countries_values = []   

In [5]:
try_keys=['Country_Region', 'Country/Region']
value="Korea"
i=0
x_data = data[286]

while (i<len(try_keys)):
#     if try_keys[i] in data:
#         # TODO: use str.extract to suppress the UserWarning
#         print(data[data[try_keys[i]].str.contains(value)])
#     else:        
#         i=i+1
    if try_keys[i] in x_data:
        tmp = x_data[x_data[try_keys[i]].str.contains(value)]
        print('yes', type(tmp))
        break
    else:
        i=i+1
    
tmp

yes <class 'pandas.core.frame.DataFrame'>


FIPS Admin2 Province_State Country_Region          Last_Update  \
350   0.0      0              0   Korea, South  2020-11-04 05:25:09   

           Lat       Long_  Confirmed  Deaths  Recovered  Active  \
350  35.907757  127.766922      26925     474      24616  1835.0   

     Combined_Key  Incidence_Rate  Case-Fatality_Ratio  
350  Korea, South       52.516928             1.760446

In [6]:
data[286].columns == data[285].columns, data[286]['Country_Region'].str.contains(value)

(array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True]),
 0       False
 1       False
 2       False
 3       False
 4       False
         ...  
 3955    False
 3956    False
 3957    False
 3958    False
 3959    False
 Name: Country_Region, Length: 3960, dtype: bool)

In [7]:
StartML.nan_columns(data[286]), StartML.nan_rows(data[286]), 

([],
 FIPS                   False
 Admin2                 False
 Province_State         False
 Country_Region         False
 Last_Update            False
 Lat                    False
 Long_                  False
 Confirmed              False
 Deaths                 False
 Recovered              False
 Active                 False
 Combined_Key           False
 Incidence_Rate         False
 Case-Fatality_Ratio    False
 dtype: bool)

In [8]:
data[286].isnull().any()

FIPS                   False
Admin2                 False
Province_State         False
Country_Region         False
Last_Update            False
Lat                    False
Long_                  False
Confirmed              False
Deaths                 False
Recovered              False
Active                 False
Combined_Key           False
Incidence_Rate         False
Case-Fatality_Ratio    False
dtype: bool

In [9]:
data[286].tail()

FIPS Admin2 Province_State      Country_Region          Last_Update  \
3955   0.0      0              0  West Bank and Gaza  2020-11-04 05:25:09   
3956   0.0      0              0      Western Sahara  2020-11-04 05:25:09   
3957   0.0      0              0               Yemen  2020-11-04 05:25:09   
3958   0.0      0              0              Zambia  2020-11-04 05:25:09   
3959   0.0      0              0            Zimbabwe  2020-11-04 05:25:09   

            Lat      Long_  Confirmed  Deaths  Recovered  Active  \
3955  31.952200  35.233200      55408     501      47744  7163.0   
3956  24.215500 -12.885800         10       1          8     1.0   
3957  15.552727  48.516388       2063     601       1375    87.0   
3958 -13.133897  27.849332      16661     349      15763   549.0   
3959 -19.015438  29.154857       8410     246       7942   222.0   

            Combined_Key  Incidence_Rate  Case-Fatality_Ratio  
3955  West Bank and Gaza     1086.129812             0.904202  
3956      Western Sahara        1.674116            10.000000  
3957               Yemen        6.916791            29.132332  
3958              Zambia       90.627937             2.094712  
3959            Zimbabwe       56.583740             2.925089

In [10]:
data[286][data[286]['Country_Region']==0]

Empty DataFrame
Columns: [FIPS, Admin2, Province_State, Country_Region, Last_Update, Lat, Long_, Confirmed, Deaths, Recovered, Active, Combined_Key, Incidence_Rate, Case-Fatality_Ratio]
Index: []

In [13]:
# for country in infected_countries_latest:
#     print(country)
# StartML.searchByValue(data[286][day], try_keys=['Country_Region', 'Country/Region'], value='Afghanistan')['Confirmed'].values
data[286][data[286]['Country_Region'].str.contains('Afghanistan')]['Confirmed'].values, 'Country_Region' in data[286], x_dat

(array([41728]),
 True,
 array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
         26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
         39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
         52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
         65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
         78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
         91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
        104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
        117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
        130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
        143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
        156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
        169, 170, 171, 172,

In [ ]:
StartML.searchByValue(data[285][day], try_keys=['Country_Region', 'Country/Region'], value='Korea')['Confirmed'].values

In [15]:
for country in infected_countries_latest:    
    # hard code for Korea
    if country == "Korea, South":
        tmp = StartML.searchByValue(data[285], try_keys=['Country_Region', 'Country/Region'], value='Korea')['Confirmed'].values
    else:
        try:
        # print(country)
        # tmp = StartML.searchByValue(data[285][day], try_keys=['Country_Region', 'Country/Region'], value=country)['Confirmed'].values
            try_keys=['Country_Region', 'Country/Region']            
            if try_keys[0] in data[285]:
                # data[data[try_keys[i]].str.contains(value)] 
                data[285][data[285]['Country_Region'].str.contains(country)]
        except KeyError:                 
            print(country)
            # print("error_day:", day, files[-(len(data[285])-day)].split('.')[0])
            sys.exit(0)
#         if tmp.size>0:
#             all_countries_values.append(tmp)
#         else:
#             # fill zero for the NaN value in data after computation of fillna
#             all_countries_values.append(np.array([0]))
#     all_countries_Confirmed[country] = all_countries_values

In [26]:
%time
# %timeit -n1000 data[285][data[285][key].str.contains('Korea')]
try_keys=['Country_Region', 'Country/Region']
for key in try_keys:
    if key in data[285]:
        data[285][data[285][key].str.contains('Korea')]

CPU times: user 4 µs, sys: 0 ns, total: 4 µs
Wall time: 8.11 µs


In [27]:
%time
for key in try_keys:
    if key in data[285]:
        data[285].loc[data[285][key].str.contains('Korea')]
# data[285]

CPU times: user 6 µs, sys: 0 ns, total: 6 µs
Wall time: 12.4 µs
